language: python
script: echo notest
deploy:
  provider: pypi
  twine: 1.12.1
  user: sashasax
  password:
    secure: eSZ+vhRkgNNugbOi4XLa/ljFsE6nAaYltuJv76JFP6OEC2NFik/LrKR11L5H2GJhnVVLwbyLKMk27IuqPbztFAWyEkBjY80gZMmqX1vk064TeEeuKqbDxL3MLt+zmXmQ9aBy0ONFVygcXl6/2GVDX3XSc956aSQnUkKBb+W0rTPdDv2qYulyjJh/fzLiNuoK8Bi2qB6uj99xHxRCVAp8gXDUPn3umnYPi/DYlyImipUtsmWmcffXAtf6EyanDrzTPF6XMY7QxVjqSv+k7teJpW10ZG8e5o+0pdzKO73rXgskcAXGvODTtZuRquF3TApaBmlRku9hynM2guCxwKaPsqi2o331nIrg74+bNCLdlLTsIglPSzJEaxkcIG1Wme8ANcqo/I1FAqByQP6UEsqXg3mAdeg6nb5aQ9CBHlqScpV7QhRPKqpcqrrIPmWmkFmng0yj9Tj2s3zglGdGmM1FZqYJIRr1zDb7WrA4ErV6l33kVl18bguec7ryGvs03ahBx4UPrJFsFouqB81kTNU10IBSL4p0YjuOiBNtllGQl8+8vYC+91kkoQR2V9gt1qtDpLp4rY/B64WPIMabjwo0FRjxXE7ZuyAJSOTotiRXQUY1kJgPK22/qrFbYmmBFAC33ILg9j74MCUbn9p29bm+vHAqckT0+nzXe53Amd5CbAE=
  on:
    branch: visualpriors
    tags: true
install:
  -  pip install -q -r requirements.txt
